package com.haiziwang.commodity.mapper;

import com.haiziwang.commodity.annotation.DataSourceTypeAnnotation;
import com.haiziwang.commodity.common.Constant;
import com.haiziwang.commodity.model.po.ConversionSpuPO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@DataSourceTypeAnnotation(value = Constant.DATASOURCE_CONVERSION)
@Repository
public interface ConversionSpuMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spu_0
     *
     * @mbg.generated Tue Jun 02 17:53:53 CST 2020
     */
    int deleteByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spu_0
     *
     * @mbg.generated Tue Jun 02 17:53:53 CST 2020
     */
    int insert(ConversionSpuPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spu_0
     *
     * @mbg.generated Tue Jun 02 17:53:53 CST 2020
     */
    int insertSelective(@Param("index")Integer index, @Param("record")ConversionSpuPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spu_0
     *
     * @mbg.generated Tue Jun 02 17:53:53 CST 2020
     */
    ConversionSpuPO selectByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spu_0
     *
     * @mbg.generated Tue Jun 02 17:53:53 CST 2020
     */
    int updateByPrimaryKeySelective(@Param("index")Integer index, @Param("record")ConversionSpuPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spu_0
     *
     * @mbg.generated Tue Jun 02 17:53:53 CST 2020
     */
    int updateByPrimaryKey(ConversionSpuPO record);

    ConversionSpuPO selectBySpuId(@Param("index")Integer index, @Param("Fspuid")String spuId,  @Param("Fcooperatorid")Long Fcooperatorid);

}
